services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    volumes:
      - maya_postgres_data:/var/lib/postgresql
    #  - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maya"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    environment:
      ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL:-admin@example.com}
      ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD:-admin123}
      ZO_MEMORY_CACHE_SIZE: "100"
      ZO_TELEMETRY_ENABLED: ${ZO_TELEMETRY_ENABLED:-false}
    ports:
      - "5080:5080"
      - "5081:5081"
      - "5082:5082"
    volumes:
      - openobserve_data:/data
    networks:
      - microservices-network

  web-api:
    build:
      context: .
      dockerfile: services/web-api/Dockerfile
    env_file:
      - .env
    container_name: webapi
    environment:
      WEB_API_PORT: 50052
      ENVIRONMENT: development
      DATABASE_URL: ${DATABASE_URL:-postgres://dbhost:dbuser@postgres:5432/dbname}
      OTEL_ENDPOINT: ${OTEL_ENDPOINT:-http://localhost:5081}
      JWT_SECRET: ${JWT_SECRET:-change_this_secret_in_production}
    ports:
      - "50052:50052"
    networks:
      - microservices-network

volumes:
  maya_postgres_data:
    driver: local
  openobserve_data:
    driver: local

networks:
  microservices-network:
    driver: bridge